# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = "https://webfixery.com"
theme = "Amperage"
pygmentsUseClasses = true
publishDir = "docs"

# Number of posts shown per page
paginate = 3

# Language sections
[languages]
    [languages.en]
        contentDir = "content"
        languageName = "English"
        languageCode = "en"
        title = "ðŸ”§ General Web Fixery â€”Â Development, APIs, Scalability, Testing"
        description = "Leveraging best practices to make the web a better place."
        weight = 1
    # [languages.es]
    #     contentDir = "content/spanish"
    #     languageName = "EspaÃ±ol"
    #     languageCode = "es"
    #     title = ""
    #     description = ""
    #     weight = 2

# Menu elements
# [[menu.main]]
#     identifier = "hugo"
#     name = "Hugo"
#     url = "https://gohugo.io"
#     weight = 10
# [[menu.main]]
#     identifier = "github"
#     name = "GitHub"
#     url = "https://github.com/asurbernardo/amperage"
#     weight = 10

# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "webfixery" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker", "amp-iframe"]

    # Google Analytics code
    googleAnalytics = ""

    # Adsense publisher code
    adsensePublisher = ""

    # Comments Iframe URL
    #commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    #facebookSite = "example"
    #twitterSite = "@example"

    # Structured data elements
    #socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    alternatePageName = "Amperage example"
    organizationLogo = "/logo.png"
    organizationName = "Asur"

    publisherName = "amperage"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60
